[tool.poetry]
name = "project-with-git"
version = "0.1.0"
description = ""
authors = ["Kasper Udengaard <meinl.cym@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
